# Introduction to Shell {#shell}

## Introduction

In this chapter, we will learn the basics of using command line. We will learn
just enough topics to be able to use Git & GitHub. If you want to learn more,
we have listed a few resources at the end of the chapter for reference.

## Directory

### Current directory

To get the current directory, use `pwd` (present working directory).

```{sh pwd}
pwd
```

### Navigate

To navigate to a sub directory, use `cd` followed by the name of the directory.
You don't need to type the full name of the directory, type a few letters and
use TAB for auto completion. In the below example, we navigate to the `docs`
directory using `cd`.

```{sh cd}
cd docs
pwd
```

To return to the main directory, use `cd ..`. Remember there is a single space
between `cd` and the 2 dots. 

```{sh cd2}
cd ..
pwd
```

### View contents

To list all the sub folders and files in a directory, use `ls`. If you want to 
list hidden folders and files, use `ls -a`.

```{sh ls}
ls
```

### Create directory

`mkdir` will create a new folder in your current directory.

```{sh mkdir}
mkdir examples
ls
```

### Remove directory

`rmdir` will remove/delete empty folders. If you have files in the folder,
you have to remove them first before removing the folder.

```{sh rmdir}
rmdir examples
ls
```

## Files

### List files

`ls` will list all the files in a folder. 

```{sh ls2}
ls
```

If you want to list hidden files, use `ls -a`.

```{sh ls3}
ls -a
```

### Copy files

To create a copy of a file, use `cp` followed by the name of the file and its
extension and the name of the copied file.

```{sh cp}
cp index.Rmd home.Rmd
ls
```

### Rename files

`mv` can be used to rename files. 

```{sh mv}
mv home.Rmd homepage.Rmd
ls
```

### Remove files

To remove files from a folder, use `rm` followed by the file name.

```{sh rm}
rm homepage.Rmd
ls
```

### Move files

To move files to a different folder or sub folder, use `mv`. In the below
example, we use `mv` to move **home.Rmd** to the **examples** folder.

```{sh mv1}
mkdir examples
cp index.Rmd home.Rmd
mv home.Rmd examples
cd examples
ls
```

### Print content

To view the contents of a file, use `cat` followed by the file name.

```{sh cat1}
cat style.css
```

`head` will return the first 10 lines of a file.

```{sh head}
head style.css
```

### Create file

To create a new file, use `touch` followed by the file name and the extension.

```{sh touch}
touch todo.txt
ls
```

If you want to add some content while creating the file, use `echo`, followed 
by the content in quotes, the `>` symbol and the file name with extension.

```{sh cat2}
echo "hello" > file1.txt
```

## Word count

`wc` will return the number of characters, words and lines in a file.

```{sh wc1}
# characters, words and lines
wc style.css
```

The following can be used to return only one of the above:

- `-c` for characters
- `-w` for words
- `-l` for lines

#### Characters

```{sh wc2}
# characters
wc -c style.css
```

#### Words

```{sh wc3}
# words
wc -w style.css 
```

#### Lines

```{sh wc4}
# lines
wc -l style.css 
```

```{sh cleanup, echo=FALSE}
rm todo.txt
rm file1.txt
rm examples/home.Rmd
rmdir examples
```